# Generated by Django 5.2.7 on 2025-11-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_email_order_name_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
