# Generated by Django 5.2.7 on 2025-11-06 14:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_paymentproof_email_paymentproof_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
