# Generated by Django 5.2.7 on 2025-11-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_paymentproof_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='screenshot',
            field=models.ImageField(upload_to='payment_proofs/'),
        ),
    ]
