# Generated by Django 5.2.7 on 2025-11-07 11:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_paymentproof_order_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
